import { PrismaClient, Product } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const products: Product[] = [
    // Whiskey
    {
      id: 1,
      sku: "WHISKEY-001",
      category: "whiskey",
      imageUrl: "/products/whiskey1.png",
      name: "Whiskey 1",
      price: 529,
      discount: "-50%",
      originalPrice: 1049,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      sku: "WHISKEY-002",
      category: "whiskey",
      imageUrl: "/products/whiskey2.png",
      name: "Whiskey 2",
      price: 579,
      discount: "-34%",
      originalPrice: 879,
      rating: 4.0,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      sku: "WHISKEY-003",
      category: "whiskey",
      imageUrl: "/products/whiskey3.png",
      name: "Whiskey 8",
      price: 779,
      discount: "-38%",
      originalPrice: 1259,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      sku: "WHISKEY-004",
      category: "whiskey",
      imageUrl: "/products/whiskey4.png",
      name: "Whiskey 8",
      price: 779,
      discount: "-38%",
      originalPrice: 1259,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      sku: "WHISKEY-005",
      category: "whiskey",
      imageUrl: "/products/whiskey5.png",
      name: "Whiskey 8",
      price: 779,
      discount: "-38%",
      originalPrice: 1259,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      sku: "WHISKEY-006",
      category: "whiskey",
      imageUrl: "/products/whiskey6.png",
      name: "Whiskey 8",
      price: 779,
      discount: "-38%",
      originalPrice: 1259,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      sku: "WHISKEY-007",
      category: "whiskey",
      imageUrl: "/products/whiskey7.png",
      name: "Whiskey 7",
      price: 699,
      discount: "-44%",
      originalPrice: 1259,
      rating: 4.2,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      sku: "WHISKEY-008",
      category: "whiskey",
      imageUrl: "/products/whiskey8.png",
      name: "Whiskey 8",
      price: 779,
      discount: "-38%",
      originalPrice: 1259,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Vodka
    {
      id: 9,
      sku: "VODKA-009",
      category: "vodka",
      imageUrl: "/products/vodka1.png",
      name: "Vodka 1",
      price: 499,
      discount: "-64%",
      originalPrice: 1399,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      sku: "VODKA-010",
      category: "vodka",
      imageUrl: "/products/vodka2.png",
      name: "Vodka 2",
      price: 549,
      discount: "-49%",
      originalPrice: 1079,
      rating: 4.3,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      sku: "VODKA-011",
      category: "vodka",
      imageUrl: "/products/vodka3.png",
      name: "Vodka 1",
      price: 499,
      discount: "-64%",
      originalPrice: 1399,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      sku: "VODKA-012",
      category: "vodka",
      imageUrl: "/products/vodka4.png",
      name: "Vodka 1",
      price: 499,
      discount: "-64%",
      originalPrice: 1399,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      sku: "VODKA-013",
      category: "vodka",
      imageUrl: "/products/vodka5.png",
      name: "Vodka 1",
      price: 499,
      discount: "-64%",
      originalPrice: 1399,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 14,
      sku: "VODKA-014",
      category: "vodka",
      imageUrl: "/products/vodka6.png",
      name: "Vodka 1",
      price: 499,
      discount: "-64%",
      originalPrice: 1399,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 15,
      sku: "VODKA-015",
      category: "vodka",
      imageUrl: "/products/vodka7.png",
      name: "Vodka 7",
      price: 649,
      discount: "-47%",
      originalPrice: 1229,
      rating: 4.6,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 16,
      sku: "VODKA-016",
      category: "vodka",
      imageUrl: "/products/vodka8.png",
      name: "Vodka 8",
      price: 679,
      discount: "-42%",
      originalPrice: 1179,
      rating: 4.9,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },

    // Champan
    {
      id: 17,
      sku: "CHAMPAN-017",
      category: "champan",
      imageUrl: "/products/champan1.png",
      name: "Champan 1",
      price: 799,
      discount: "-55%",
      originalPrice: 1799,
      rating: 4.8,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 18,
      sku: "CHAMPAN-018",
      category: "champan",
      imageUrl: "/products/champan2.png",
      name: "Champan 2",
      price: 849,
      discount: "-50%",
      originalPrice: 1699,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 19,
      sku: "CHAMPAN-019",
      category: "champan",
      imageUrl: "/products/champan3.png",
      name: "Champan 2",
      price: 849,
      discount: "-50%",
      originalPrice: 1699,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 20,
      sku: "CHAMPAN-020",
      category: "champan",
      imageUrl: "/products/champan4.png",
      name: "Champan 2",
      price: 849,
      discount: "-50%",
      originalPrice: 1699,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 21,
      sku: "CHAMPAN-021",
      category: "champan",
      imageUrl: "/products/champan5.png",
      name: "Champan 2",
      price: 849,
      discount: "-50%",
      originalPrice: 1699,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 22,
      sku: "CHAMPAN-022",
      category: "champan",
      imageUrl: "/products/champan6.png",
      name: "Champan 2",
      price: 849,
      discount: "-50%",
      originalPrice: 1699,
      rating: 4.5,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 23,
      sku: "CHAMPAN-023",
      category: "champan",
      imageUrl: "/products/champan7.png",
      name: "Champan 7",
      price: 899,
      discount: "-45%",
      originalPrice: 1629,
      rating: 4.7,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 24,
      sku: "CHAMPAN-024",
      category: "champan",
      imageUrl: "/products/champan8.png",
      name: "Champan 8",
      price: 949,
      discount: "-40%",
      originalPrice: 1579,
      rating: 4.9,
      description: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: {},
      create: product,
    });
  }

  console.log("Database seeded successfully");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
