// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010002_user_role.sql

package db

import (
	"context"
)

const createUserRole = `-- name: CreateUserRole :one
INSERT    INTO user_roles (role_name)
VALUES    (?)
RETURNING role_id, role_name
`

// Create Role
func (q *Queries) CreateUserRole(ctx context.Context, roleName string) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRole, roleName)
	var i UserRole
	err := row.Scan(&i.RoleID, &i.RoleName)
	return i, err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE    FROM user_roles
WHERE     role_id = ?
`

// Delete Role
func (q *Queries) DeleteUserRole(ctx context.Context, roleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, roleID)
	return err
}

const getUserRoleByID = `-- name: GetUserRoleByID :one
SELECT    role_id, role_name
FROM      user_roles
WHERE     role_id = ?
`

// Get Role by ID
func (q *Queries) GetUserRoleByID(ctx context.Context, roleID int64) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByID, roleID)
	var i UserRole
	err := row.Scan(&i.RoleID, &i.RoleName)
	return i, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT    role_id, role_name
FROM      user_roles
ORDER BY  role_name
`

// Get All Roles
func (q *Queries) ListUserRoles(ctx context.Context) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, listUserRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.RoleID, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRoleName = `-- name: UpdateUserRoleName :exec
UPDATE    user_roles
SET       role_name = ?
WHERE     role_id = ?
`

// Update Role Name
func (q *Queries) UpdateUserRoleName(ctx context.Context, roleName string, roleID int64) error {
	_, err := q.db.ExecContext(ctx, updateUserRoleName, roleName, roleID)
	return err
}
