// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010001_users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT    INTO users (email, password_hash, NAME)
VALUES    (?, ?, ?)
RETURNING user_id, email, password_hash, name, created_at, last_login, is_active
`

// Create User
func (q *Queries) CreateUser(ctx context.Context, email string, passwordHash sql.NullString, name sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email, passwordHash, name)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastLogin,
		&i.IsActive,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE    users
SET       is_active = 0
WHERE     user_id = ?
`

// Deactivate User
func (q *Queries) DeactivateUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE    FROM users
WHERE     user_id = ?
`

// Delete User
func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT    user_id, email, password_hash, name, created_at, last_login, is_active
FROM      users
WHERE     email = ?
`

// Get User by Email
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastLogin,
		&i.IsActive,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT    user_id, email, password_hash, name, created_at, last_login, is_active
FROM      users
WHERE     user_id = ?
`

// Get User by ID
func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastLogin,
		&i.IsActive,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE    users
SET       email = COALESCE(?, email),
          password_hash = COALESCE(?, password_hash),
          NAME = COALESCE(?, NAME),
          last_login = COALESCE(?, last_login),
          is_active = COALESCE(?, is_active)
WHERE     user_id = ?
RETURNING user_id, email, password_hash, name, created_at, last_login, is_active
`

type UpdateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	LastLogin    sql.NullTime   `json:"last_login"`
	IsActive     sql.NullInt64  `json:"is_active"`
	UserID       int64          `json:"user_id"`
}

// Update User Details
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.LastLogin,
		arg.IsActive,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastLogin,
		&i.IsActive,
	)
	return i, err
}
