// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010004_user_addresses.sql

package db

import (
	"context"
	"database/sql"
)

const createUserAddress = `-- name: CreateUserAddress :one
INSERT    INTO user_addresses (user_id, encrypted_address, city, region, phone, is_default)
VALUES    (?, ?, ?, ?, ?, ?)
RETURNING address_id, user_id, encrypted_address, city, region, phone, is_default, created_at
`

type CreateUserAddressParams struct {
	UserID           int64         `json:"user_id"`
	EncryptedAddress string        `json:"encrypted_address"`
	City             string        `json:"city"`
	Region           string        `json:"region"`
	Phone            []byte        `json:"phone"`
	IsDefault        sql.NullInt64 `json:"is_default"`
}

// Add Address
func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRowContext(ctx, createUserAddress,
		arg.UserID,
		arg.EncryptedAddress,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.EncryptedAddress,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserAddress = `-- name: DeleteUserAddress :exec
DELETE    FROM user_addresses
WHERE     address_id = ?
`

// Delete Address
func (q *Queries) DeleteUserAddress(ctx context.Context, addressID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserAddress, addressID)
	return err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT    address_id, user_id, encrypted_address, city, region, phone, is_default, created_at
FROM      user_addresses
WHERE     user_id = ?
ORDER BY  is_default DESC,
          created_at DESC
`

// Get User Addresses
func (q *Queries) GetUserAddresses(ctx context.Context, userID int64) ([]UserAddress, error) {
	rows, err := q.db.QueryContext(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.AddressID,
			&i.UserID,
			&i.EncryptedAddress,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultUserAddress = `-- name: SetDefaultUserAddress :exec
UPDATE    user_addresses
SET       is_default = CASE
                    WHEN address_id = ? THEN 1
                    ELSE 0
          END
WHERE     user_id = ?
`

// Set Default Address
func (q *Queries) SetDefaultUserAddress(ctx context.Context, addressID int64, userID int64) error {
	_, err := q.db.ExecContext(ctx, setDefaultUserAddress, addressID, userID)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE    user_addresses
SET       encrypted_address = COALESCE(?, encrypted_address),
          city = COALESCE(?, city),
          region = COALESCE(?, region),
          phone = COALESCE(?, phone),
          is_default = COALESCE(?, is_default)
WHERE     address_id = ?
RETURNING address_id, user_id, encrypted_address, city, region, phone, is_default, created_at
`

type UpdateUserAddressParams struct {
	EncryptedAddress string        `json:"encrypted_address"`
	City             string        `json:"city"`
	Region           string        `json:"region"`
	Phone            []byte        `json:"phone"`
	IsDefault        sql.NullInt64 `json:"is_default"`
	AddressID        int64         `json:"address_id"`
}

// Update Address
func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRowContext(ctx, updateUserAddress,
		arg.EncryptedAddress,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.IsDefault,
		arg.AddressID,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.EncryptedAddress,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
