// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010003_user_roles_assignments.sql

package db

import (
	"context"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT    INTO user_role_assignments (user_id, role_id)
VALUES    (?, ?)
`

// Assign Role to User
func (q *Queries) AssignUserRole(ctx context.Context, userID int64, roleID int64) error {
	_, err := q.db.ExecContext(ctx, assignUserRole, userID, roleID)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT    r.role_id, r.role_name
FROM      user_roles r
JOIN      user_role_assignments a ON r.role_id = a.role_id
WHERE     a.user_id = ?
`

// Get User Roles
func (q *Queries) GetUserRoles(ctx context.Context, userID int64) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.RoleID, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserRole = `-- name: HasUserRole :one
SELECT    EXISTS (
          SELECT    1
          FROM      user_role_assignments
          WHERE     user_id = ? AND      
                    role_id = ?
          )
`

// Check Role Assignment
func (q *Queries) HasUserRole(ctx context.Context, userID int64, roleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasUserRole, userID, roleID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE    FROM user_role_assignments
WHERE     user_id = ? AND      
          role_id = ?
`

// Remove Role from User
func (q *Queries) RemoveUserRole(ctx context.Context, userID int64, roleID int64) error {
	_, err := q.db.ExecContext(ctx, removeUserRole, userID, roleID)
	return err
}
