// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 010005_user_social_logins.sql.sql

package db

import (
	"context"
)

const addUserSocialLogin = `-- name: AddUserSocialLogin :exec
INSERT    INTO user_social_logins (user_id, provider, provider_id)
VALUES    (?, ?, ?) ON CONFLICT (provider, provider_id)
DO        NOTHING
`

// Add Social Login
func (q *Queries) AddUserSocialLogin(ctx context.Context, userID int64, provider string, providerID string) error {
	_, err := q.db.ExecContext(ctx, addUserSocialLogin, userID, provider, providerID)
	return err
}

const findUserBySocial = `-- name: FindUserBySocial :one
SELECT    u.user_id, u.email, u.password_hash, u.name, u.created_at, u.last_login, u.is_active
FROM      users u
JOIN      user_social_logins s ON u.user_id = s.user_id
WHERE     s.provider = ? AND      
          s.provider_id = ?
`

// Find User by Social Login
func (q *Queries) FindUserBySocial(ctx context.Context, provider string, providerID string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserBySocial, provider, providerID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastLogin,
		&i.IsActive,
	)
	return i, err
}

const getUserSocialLogins = `-- name: GetUserSocialLogins :many
SELECT    social_id, user_id, provider, provider_id
FROM      user_social_logins
WHERE     user_id = ?
`

// Get Social Logins by User
func (q *Queries) GetUserSocialLogins(ctx context.Context, userID int64) ([]UserSocialLogin, error) {
	rows, err := q.db.QueryContext(ctx, getUserSocialLogins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSocialLogin
	for rows.Next() {
		var i UserSocialLogin
		if err := rows.Scan(
			&i.SocialID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserSocialLogin = `-- name: RemoveUserSocialLogin :exec
DELETE    FROM user_social_logins
WHERE     social_id = ?
`

// Remove Social Login
func (q *Queries) RemoveUserSocialLogin(ctx context.Context, socialID int64) error {
	_, err := q.db.ExecContext(ctx, removeUserSocialLogin, socialID)
	return err
}
