// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 020004_product_variants.sql

package db

import (
	"context"
	"database/sql"
)

const createProductVariant = `-- name: CreateProductVariant :one
INSERT    INTO product_variants (product_id, sku, price, attributes, allow_backorder)
VALUES    (?, ?, ?, ?, ?)
RETURNING variant_id, product_id, sku, price, attributes, allow_backorder
`

type CreateProductVariantParams struct {
	ProductID      int64         `json:"product_id"`
	Sku            string        `json:"sku"`
	Price          float64       `json:"price"`
	Attributes     string        `json:"attributes"`
	AllowBackorder sql.NullInt64 `json:"allow_backorder"`
}

// Create Variant
func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, createProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Price,
		arg.Attributes,
		arg.AllowBackorder,
	)
	var i ProductVariant
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.Sku,
		&i.Price,
		&i.Attributes,
		&i.AllowBackorder,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE    FROM product_variants
WHERE     variant_id = ?
`

// Delete Variant
func (q *Queries) DeleteProductVariant(ctx context.Context, variantID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProductVariant, variantID)
	return err
}

const getProductVariantBySKU = `-- name: GetProductVariantBySKU :one
SELECT    variant_id, product_id, sku, price, attributes, allow_backorder
FROM      product_variants
WHERE     sku = ?
`

// Get Variant by SKU
func (q *Queries) GetProductVariantBySKU(ctx context.Context, sku string) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantBySKU, sku)
	var i ProductVariant
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.Sku,
		&i.Price,
		&i.Attributes,
		&i.AllowBackorder,
	)
	return i, err
}

const getProductVariants = `-- name: GetProductVariants :many
SELECT    variant_id, product_id, sku, price, attributes, allow_backorder
FROM      product_variants
WHERE     product_id = ?
ORDER BY  sku
`

// Get Product Variants
func (q *Queries) GetProductVariants(ctx context.Context, productID int64) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, getProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Sku,
			&i.Price,
			&i.Attributes,
			&i.AllowBackorder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE    product_variants
SET       price = COALESCE(?, price),
          attributes = COALESCE(?, attributes),
          allow_backorder = COALESCE(?, allow_backorder)
WHERE     variant_id = ?
RETURNING variant_id, product_id, sku, price, attributes, allow_backorder
`

type UpdateProductVariantParams struct {
	Price          float64       `json:"price"`
	Attributes     string        `json:"attributes"`
	AllowBackorder sql.NullInt64 `json:"allow_backorder"`
	VariantID      int64         `json:"variant_id"`
}

// Update Variant
func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, updateProductVariant,
		arg.Price,
		arg.Attributes,
		arg.AllowBackorder,
		arg.VariantID,
	)
	var i ProductVariant
	err := row.Scan(
		&i.VariantID,
		&i.ProductID,
		&i.Sku,
		&i.Price,
		&i.Attributes,
		&i.AllowBackorder,
	)
	return i, err
}
