// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 020001_categories.sql

package db

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT    INTO categories (NAME, parent_id)
VALUES    (?, ?)
RETURNING category_id, name, parent_id
`

// Create Category
func (q *Queries) CreateCategory(ctx context.Context, name string, parentID sql.NullInt64) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, name, parentID)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.ParentID)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE    FROM categories
WHERE     category_id = ?
`

// Delete Category (automatically removes product associations via CASCADE)
func (q *Queries) DeleteCategory(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, categoryID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE    categories
SET       NAME = COALESCE(?, NAME),
          parent_id = COALESCE(?, parent_id)
WHERE     category_id = ?
RETURNING category_id, name, parent_id
`

// Update Category
func (q *Queries) UpdateCategory(ctx context.Context, name string, parentID sql.NullInt64, categoryID int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, name, parentID, categoryID)
	var i Category
	err := row.Scan(&i.CategoryID, &i.Name, &i.ParentID)
	return i, err
}
