// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 020003_product_categories.sql

package db

import (
	"context"
)

const assignProductCategory = `-- name: AssignProductCategory :exec
INSERT    INTO product_categories (product_id, category_id)
VALUES    (?, ?) ON CONFLICT
DO        NOTHING
`

// Assign Category to Product
func (q *Queries) AssignProductCategory(ctx context.Context, productID int64, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, assignProductCategory, productID, categoryID)
	return err
}

const getCategoryProducts = `-- name: GetCategoryProducts :many
SELECT    p.product_id, p.name, p.description, p.base_price, p.created_at
FROM      products p
JOIN      product_categories pc ON p.product_id = pc.product_id
WHERE     pc.category_id = ?
`

// Get Products in Category
func (q *Queries) GetCategoryProducts(ctx context.Context, categoryID int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryProducts, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductCategories = `-- name: GetProductCategories :many
SELECT    c.category_id, c.name, c.parent_id
FROM      categories c
JOIN      product_categories pc ON c.category_id = pc.category_id
WHERE     pc.product_id = ?
`

// Get Product Categories
func (q *Queries) GetProductCategories(ctx context.Context, productID int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getProductCategories, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductCategory = `-- name: RemoveProductCategory :exec
DELETE    FROM product_categories
WHERE     product_id = ? AND      
          category_id = ?
`

// Remove Category from Product
func (q *Queries) RemoveProductCategory(ctx context.Context, productID int64, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, removeProductCategory, productID, categoryID)
	return err
}
