// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 020002_products.sql

package db

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT    INTO products (NAME, description, base_price)
VALUES    (?, ?, ?)
RETURNING product_id, name, description, base_price, created_at
`

// Create Product
func (q *Queries) CreateProduct(ctx context.Context, name string, description sql.NullString, basePrice float64) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, name, description, basePrice)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE    FROM products
WHERE     product_id = ?
`

// Delete Product (cascades to variants/categories)
func (q *Queries) DeleteProduct(ctx context.Context, productID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, productID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT    product_id, name, description, base_price, created_at
FROM      products
WHERE     product_id = ?
`

// Get Product by ID
func (q *Queries) GetProduct(ctx context.Context, productID int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT    product_id, name, description, base_price, created_at
FROM      products
ORDER BY  created_at DESC
LIMIT     ?
OFFSET    ?
`

// List Products with Pagination
func (q *Queries) ListProducts(ctx context.Context, limit int64, offset int64) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE    products
SET       NAME = COALESCE(?, NAME),
          description = COALESCE(?, description),
          base_price = COALESCE(?, base_price)
WHERE     product_id = ?
RETURNING product_id, name, description, base_price, created_at
`

type UpdateProductParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   float64        `json:"base_price"`
	ProductID   int64          `json:"product_id"`
}

// Update Product Details
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.BasePrice,
		arg.ProductID,
	)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Description,
		&i.BasePrice,
		&i.CreatedAt,
	)
	return i, err
}
