// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 020005_product_attributes.sql

package db

import (
	"context"
)

const addProductAttribute = `-- name: AddProductAttribute :exec
INSERT    INTO product_attributes (product_id, attribute_name, attribute_value)
VALUES    (?, ?, ?) ON CONFLICT (product_id, attribute_name)
DO       
UPDATE   
SET       attribute_value = excluded.attribute_value
`

// Add Attribute
func (q *Queries) AddProductAttribute(ctx context.Context, productID int64, attributeName string, attributeValue string) error {
	_, err := q.db.ExecContext(ctx, addProductAttribute, productID, attributeName, attributeValue)
	return err
}

const getProductAttributes = `-- name: GetProductAttributes :many
SELECT    attribute_id, product_id, attribute_name, attribute_value
FROM      product_attributes
WHERE     product_id = ?
`

// Get Product Attributes
func (q *Queries) GetProductAttributes(ctx context.Context, productID int64) ([]ProductAttribute, error) {
	rows, err := q.db.QueryContext(ctx, getProductAttributes, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttribute
	for rows.Next() {
		var i ProductAttribute
		if err := rows.Scan(
			&i.AttributeID,
			&i.ProductID,
			&i.AttributeName,
			&i.AttributeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductAttribute = `-- name: RemoveProductAttribute :exec
DELETE    FROM product_attributes
WHERE     product_id = ? AND      
          attribute_name = ?
`

// Remove Attribute
func (q *Queries) RemoveProductAttribute(ctx context.Context, productID int64, attributeName string) error {
	_, err := q.db.ExecContext(ctx, removeProductAttribute, productID, attributeName)
	return err
}

const searchProductByAttribute = `-- name: SearchProductByAttribute :many
SELECT    p.product_id, p.name, p.description, p.base_price, p.created_at
FROM      products p
JOIN      product_attributes pa ON p.product_id = pa.product_id
WHERE     pa.attribute_name = ? AND      
          pa.attribute_value = ?
`

// Search by Attribute
func (q *Queries) SearchProductByAttribute(ctx context.Context, attributeName string, attributeValue string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProductByAttribute, attributeName, attributeValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.Description,
			&i.BasePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
