// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 030001_inventory_locations.sql

package db

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT    INTO inventory_locations (NAME, city, region)
VALUES    (?, ?, ?)
RETURNING location_id, name, city, region
`

// Create new inventory location
func (q *Queries) CreateLocation(ctx context.Context, name string, city string, region string) (InventoryLocation, error) {
	row := q.db.QueryRowContext(ctx, createLocation, name, city, region)
	var i InventoryLocation
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.City,
		&i.Region,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
DELETE    FROM inventory_locations
WHERE     location_id = ?
`

// Delete location (cascades to stock records)
func (q *Queries) DeleteLocation(ctx context.Context, locationID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, locationID)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT    location_id, name, city, region
FROM      inventory_locations
WHERE     location_id = ?
`

// Get location by ID
func (q *Queries) GetLocationByID(ctx context.Context, locationID int64) (InventoryLocation, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, locationID)
	var i InventoryLocation
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.City,
		&i.Region,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT    location_id, name, city, region
FROM      inventory_locations
ORDER BY  region,
          city,
          NAME
`

// List all locations
func (q *Queries) ListLocations(ctx context.Context) ([]InventoryLocation, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryLocation
	for rows.Next() {
		var i InventoryLocation
		if err := rows.Scan(
			&i.LocationID,
			&i.Name,
			&i.City,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE    inventory_locations
SET       NAME = COALESCE(?, NAME),
          city = COALESCE(?, city),
          region = COALESCE(?, region)
WHERE     location_id = ?
RETURNING location_id, name, city, region
`

type UpdateLocationParams struct {
	Name       string `json:"name"`
	City       string `json:"city"`
	Region     string `json:"region"`
	LocationID int64  `json:"location_id"`
}

// Update location details
func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (InventoryLocation, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.Name,
		arg.City,
		arg.Region,
		arg.LocationID,
	)
	var i InventoryLocation
	err := row.Scan(
		&i.LocationID,
		&i.Name,
		&i.City,
		&i.Region,
	)
	return i, err
}
