// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 030002_stock.sql

package db

import (
	"context"
	"database/sql"
)

const adjustStock = `-- name: AdjustStock :exec
UPDATE    stock
SET       quantity = quantity + ?
WHERE     variant_id = ? AND      
          location_id = ?
`

// Adjust stock (relative)
func (q *Queries) AdjustStock(ctx context.Context, quantity int64, variantID int64, locationID int64) error {
	_, err := q.db.ExecContext(ctx, adjustStock, quantity, variantID, locationID)
	return err
}

const createStockEntry = `-- name: CreateStockEntry :one
INSERT    INTO stock (variant_id, location_id, quantity, low_stock_threshold)
VALUES    (?, ?, ?, ?)
RETURNING stock_id, variant_id, location_id, quantity, low_stock_threshold, low_stock_alert
`

type CreateStockEntryParams struct {
	VariantID         int64         `json:"variant_id"`
	LocationID        int64         `json:"location_id"`
	Quantity          int64         `json:"quantity"`
	LowStockThreshold sql.NullInt64 `json:"low_stock_threshold"`
}

// Create stock entry
func (q *Queries) CreateStockEntry(ctx context.Context, arg CreateStockEntryParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, createStockEntry,
		arg.VariantID,
		arg.LocationID,
		arg.Quantity,
		arg.LowStockThreshold,
	)
	var i Stock
	err := row.Scan(
		&i.StockID,
		&i.VariantID,
		&i.LocationID,
		&i.Quantity,
		&i.LowStockThreshold,
		&i.LowStockAlert,
	)
	return i, err
}

const deleteStockEntry = `-- name: DeleteStockEntry :exec
DELETE    FROM stock
WHERE     stock_id = ?
`

// Delete stock entry
func (q *Queries) DeleteStockEntry(ctx context.Context, stockID int64) error {
	_, err := q.db.ExecContext(ctx, deleteStockEntry, stockID)
	return err
}

const getStockEntry = `-- name: GetStockEntry :one
SELECT    stock_id, variant_id, location_id, quantity, low_stock_threshold, low_stock_alert
FROM      stock
WHERE     variant_id = ? AND      
          location_id = ?
`

// Get stock for variant at location
func (q *Queries) GetStockEntry(ctx context.Context, variantID int64, locationID int64) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockEntry, variantID, locationID)
	var i Stock
	err := row.Scan(
		&i.StockID,
		&i.VariantID,
		&i.LocationID,
		&i.Quantity,
		&i.LowStockThreshold,
		&i.LowStockAlert,
	)
	return i, err
}

const getVariantStock = `-- name: GetVariantStock :many
SELECT    s.stock_id, s.variant_id, s.location_id, s.quantity, s.low_stock_threshold, s.low_stock_alert,
          l.name AS location_name,
          l.city AS location_city
FROM      stock s
JOIN      inventory_locations l ON s.location_id = l.location_id
WHERE     variant_id = ?
`

type GetVariantStockRow struct {
	StockID           int64         `json:"stock_id"`
	VariantID         int64         `json:"variant_id"`
	LocationID        int64         `json:"location_id"`
	Quantity          int64         `json:"quantity"`
	LowStockThreshold sql.NullInt64 `json:"low_stock_threshold"`
	LowStockAlert     sql.NullInt64 `json:"low_stock_alert"`
	LocationName      string        `json:"location_name"`
	LocationCity      string        `json:"location_city"`
}

// Get all stock for variant
func (q *Queries) GetVariantStock(ctx context.Context, variantID int64) ([]GetVariantStockRow, error) {
	rows, err := q.db.QueryContext(ctx, getVariantStock, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariantStockRow
	for rows.Next() {
		var i GetVariantStockRow
		if err := rows.Scan(
			&i.StockID,
			&i.VariantID,
			&i.LocationID,
			&i.Quantity,
			&i.LowStockThreshold,
			&i.LowStockAlert,
			&i.LocationName,
			&i.LocationCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStock = `-- name: ListLowStock :many
SELECT    s.stock_id, s.variant_id, s.location_id, s.quantity, s.low_stock_threshold, s.low_stock_alert,
          v.sku,
          p.name AS product_name,
          l.name AS location_name
FROM      stock s
JOIN      product_variants v ON s.variant_id = v.variant_id
JOIN      products p ON v.product_id = p.product_id
JOIN      inventory_locations l ON s.location_id = l.location_id
WHERE     s.low_stock_alert = 1
`

type ListLowStockRow struct {
	StockID           int64         `json:"stock_id"`
	VariantID         int64         `json:"variant_id"`
	LocationID        int64         `json:"location_id"`
	Quantity          int64         `json:"quantity"`
	LowStockThreshold sql.NullInt64 `json:"low_stock_threshold"`
	LowStockAlert     sql.NullInt64 `json:"low_stock_alert"`
	Sku               string        `json:"sku"`
	ProductName       string        `json:"product_name"`
	LocationName      string        `json:"location_name"`
}

// Get low stock alerts
func (q *Queries) ListLowStock(ctx context.Context) ([]ListLowStockRow, error) {
	rows, err := q.db.QueryContext(ctx, listLowStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowStockRow
	for rows.Next() {
		var i ListLowStockRow
		if err := rows.Scan(
			&i.StockID,
			&i.VariantID,
			&i.LocationID,
			&i.Quantity,
			&i.LowStockThreshold,
			&i.LowStockAlert,
			&i.Sku,
			&i.ProductName,
			&i.LocationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStockQuantity = `-- name: SetStockQuantity :exec
UPDATE    stock
SET       quantity = ?
WHERE     variant_id = ? AND      
          location_id = ?
`

// Update stock quantity (absolute)
func (q *Queries) SetStockQuantity(ctx context.Context, quantity int64, variantID int64, locationID int64) error {
	_, err := q.db.ExecContext(ctx, setStockQuantity, quantity, variantID, locationID)
	return err
}
