// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 040001_orders.sql

package db

import (
	"context"
	"database/sql"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE    orders
SET       current_status_id = (
          SELECT    status_id
          FROM      order_status
          WHERE     status_name = 'cancelled'
          )
WHERE     order_id = ?
`

// Cancel order
func (q *Queries) CancelOrder(ctx context.Context, orderID int64) error {
	_, err := q.db.ExecContext(ctx, cancelOrder, orderID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT    INTO orders (user_id, guest_order_id, total, current_status_id)
VALUES    (
          ?,
          ?,
          ?,
          (
          SELECT    status_id
          FROM      order_status
          WHERE     status_name = 'pending'
          )
          )
RETURNING order_id, user_id, guest_order_id, total, created_at, current_status_id
`

// Create order
func (q *Queries) CreateOrder(ctx context.Context, userID sql.NullInt64, guestOrderID sql.NullInt64, total float64) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, userID, guestOrderID, total)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.GuestOrderID,
		&i.Total,
		&i.CreatedAt,
		&i.CurrentStatusID,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT    o.order_id, o.user_id, o.guest_order_id, o.total, o.created_at, o.current_status_id,
          u.email       AS user_email,
          g.email       AS guest_email,
          s.status_name
FROM      orders o
LEFT JOIN users u ON o.user_id = u.user_id
LEFT JOIN guest_orders g ON o.guest_order_id = g.guest_order_id
JOIN      order_status s ON o.current_status_id = s.status_id
WHERE     o.order_id = ?
`

type GetOrderRow struct {
	OrderID         int64         `json:"order_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	GuestOrderID    sql.NullInt64 `json:"guest_order_id"`
	Total           float64       `json:"total"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	CurrentStatusID int64         `json:"current_status_id"`
	UserEmail       string        `json:"user_email"`
	GuestEmail      string        `json:"guest_email"`
	StatusName      string        `json:"status_name"`
}

// Get order by ID
func (q *Queries) GetOrder(ctx context.Context, orderID int64) (GetOrderRow, error) {
	row := q.db.QueryRowContext(ctx, getOrder, orderID)
	var i GetOrderRow
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.GuestOrderID,
		&i.Total,
		&i.CreatedAt,
		&i.CurrentStatusID,
		&i.UserEmail,
		&i.GuestEmail,
		&i.StatusName,
	)
	return i, err
}

const listGuestOrders = `-- name: ListGuestOrders :many
SELECT    order_id, user_id, guest_order_id, total, created_at, current_status_id
FROM      orders
WHERE     guest_order_id = ?
ORDER BY  created_at DESC
`

// List guest orders
func (q *Queries) ListGuestOrders(ctx context.Context, guestOrderID sql.NullInt64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listGuestOrders, guestOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.GuestOrderID,
			&i.Total,
			&i.CreatedAt,
			&i.CurrentStatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrders = `-- name: ListUserOrders :many
SELECT    order_id, user_id, guest_order_id, total, created_at, current_status_id
FROM      orders
WHERE     user_id = ?
ORDER BY  created_at DESC
`

// List user orders
func (q *Queries) ListUserOrders(ctx context.Context, userID sql.NullInt64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.GuestOrderID,
			&i.Total,
			&i.CreatedAt,
			&i.CurrentStatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesOrderReport = `-- name: SalesOrderReport :many
SELECT    DATE (created_at) AS date,
          COUNT(*)          AS order_count,
          SUM(total)        AS total_sales
FROM      orders
WHERE     created_at BETWEEN ? AND ?
GROUP BY  DATE (created_at)
ORDER BY  DATE (created_at)
`

type SalesOrderReportRow struct {
	Date       interface{}     `json:"date"`
	OrderCount int64           `json:"order_count"`
	TotalSales sql.NullFloat64 `json:"total_sales"`
}

// Sales report
func (q *Queries) SalesOrderReport(ctx context.Context, fromCreatedAt sql.NullTime, toCreatedAt sql.NullTime) ([]SalesOrderReportRow, error) {
	rows, err := q.db.QueryContext(ctx, salesOrderReport, fromCreatedAt, toCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesOrderReportRow
	for rows.Next() {
		var i SalesOrderReportRow
		if err := rows.Scan(&i.Date, &i.OrderCount, &i.TotalSales); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE    orders
SET       current_status_id = ?
WHERE     order_id = ?
RETURNING order_id, user_id, guest_order_id, total, created_at, current_status_id
`

// Update order status
func (q *Queries) UpdateOrderStatus(ctx context.Context, currentStatusID int64, orderID int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, currentStatusID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.GuestOrderID,
		&i.Total,
		&i.CreatedAt,
		&i.CurrentStatusID,
	)
	return i, err
}
