// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 040003_guest_orders.sql

package db

import (
	"context"
)

const createGuestOrder = `-- name: CreateGuestOrder :one
INSERT    INTO guest_orders (email, encrypted_address)
VALUES    (?, ?)
RETURNING guest_order_id, email, encrypted_address, created_at
`

// Create guest order
func (q *Queries) CreateGuestOrder(ctx context.Context, email string, encryptedAddress string) (GuestOrder, error) {
	row := q.db.QueryRowContext(ctx, createGuestOrder, email, encryptedAddress)
	var i GuestOrder
	err := row.Scan(
		&i.GuestOrderID,
		&i.Email,
		&i.EncryptedAddress,
		&i.CreatedAt,
	)
	return i, err
}

const getGuestOrder = `-- name: GetGuestOrder :one
SELECT    guest_order_id, email, encrypted_address, created_at
FROM      guest_orders
WHERE     guest_order_id = ?
`

// Get guest order
func (q *Queries) GetGuestOrder(ctx context.Context, guestOrderID int64) (GuestOrder, error) {
	row := q.db.QueryRowContext(ctx, getGuestOrder, guestOrderID)
	var i GuestOrder
	err := row.Scan(
		&i.GuestOrderID,
		&i.Email,
		&i.EncryptedAddress,
		&i.CreatedAt,
	)
	return i, err
}
