// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 040004_order_status_history.sql

package db

import (
	"context"
	"database/sql"
)

const getOrderHistory = `-- name: GetOrderHistory :many
SELECT    h.history_id, h.order_id, h.status_id, h.created_at,
          s.status_name
FROM      order_status_history h
JOIN      order_status s ON h.status_id = s.status_id
WHERE     order_id = ?
ORDER BY  created_at DESC
`

type GetOrderHistoryRow struct {
	HistoryID  int64        `json:"history_id"`
	OrderID    int64        `json:"order_id"`
	StatusID   int64        `json:"status_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	StatusName string       `json:"status_name"`
}

// Get order history
func (q *Queries) GetOrderHistory(ctx context.Context, orderID int64) ([]GetOrderHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderHistoryRow
	for rows.Next() {
		var i GetOrderHistoryRow
		if err := rows.Scan(
			&i.HistoryID,
			&i.OrderID,
			&i.StatusID,
			&i.CreatedAt,
			&i.StatusName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStatusChange = `-- name: RecordStatusChange :exec
INSERT    INTO order_status_history (order_id, status_id)
VALUES    (?, ?)
`

func (q *Queries) RecordStatusChange(ctx context.Context, orderID int64, statusID int64) error {
	_, err := q.db.ExecContext(ctx, recordStatusChange, orderID, statusID)
	return err
}
