// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 040002_order_status.sql

package db

import (
	"context"
)

const seedOrderStatuses = `-- name: SeedOrderStatuses :exec


SELECT    status_id, status_name
FROM      order_status
ORDER BY  status_id
`

// Predefined statuses (initial data migration)
// List all statuses
func (q *Queries) SeedOrderStatuses(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedOrderStatuses)
	return err
}
