// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 040005_order_items.sql

package db

import (
	"context"
	"database/sql"
)

const addOrderItem = `-- name: AddOrderItem :one
INSERT    INTO order_items (order_id, variant_id, quantity, price)
VALUES    (?, ?, ?, ?)
RETURNING item_id, order_id, variant_id, quantity, price
`

type AddOrderItemParams struct {
	OrderID   int64   `json:"order_id"`
	VariantID int64   `json:"variant_id"`
	Quantity  int64   `json:"quantity"`
	Price     float64 `json:"price"`
}

// Add item to order
func (q *Queries) AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, addOrderItem,
		arg.OrderID,
		arg.VariantID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ItemID,
		&i.OrderID,
		&i.VariantID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT    i.item_id, i.order_id, i.variant_id, i.quantity, i.price,
          v.sku,
          p.name       AS product_name,
          v.attributes
FROM      order_items i
JOIN      product_variants v ON i.variant_id = v.variant_id
JOIN      products p ON v.product_id = p.product_id
WHERE     order_id = ?
`

type GetOrderItemsRow struct {
	ItemID      int64   `json:"item_id"`
	OrderID     int64   `json:"order_id"`
	VariantID   int64   `json:"variant_id"`
	Quantity    int64   `json:"quantity"`
	Price       float64 `json:"price"`
	Sku         string  `json:"sku"`
	ProductName string  `json:"product_name"`
	Attributes  string  `json:"attributes"`
}

// Get order items
func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.OrderID,
			&i.VariantID,
			&i.Quantity,
			&i.Price,
			&i.Sku,
			&i.ProductName,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const popularProductOrders = `-- name: PopularProductOrders :many
SELECT    v.variant_id,
          v.sku,
          p.name,
          SUM(i.quantity) AS total_sold
FROM      order_items i
JOIN      product_variants v ON i.variant_id = v.variant_id
JOIN      products p ON v.product_id = p.product_id
GROUP BY  v.variant_id
ORDER BY  total_sold DESC
LIMIT     ?
`

type PopularProductOrdersRow struct {
	VariantID int64           `json:"variant_id"`
	Sku       string          `json:"sku"`
	Name      string          `json:"name"`
	TotalSold sql.NullFloat64 `json:"total_sold"`
}

// Popular products
func (q *Queries) PopularProductOrders(ctx context.Context, limit int64) ([]PopularProductOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, popularProductOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PopularProductOrdersRow
	for rows.Next() {
		var i PopularProductOrdersRow
		if err := rows.Scan(
			&i.VariantID,
			&i.Sku,
			&i.Name,
			&i.TotalSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrderItem = `-- name: RemoveOrderItem :exec
DELETE    FROM order_items
WHERE     item_id = ?
`

// Remove item from order
func (q *Queries) RemoveOrderItem(ctx context.Context, itemID int64) error {
	_, err := q.db.ExecContext(ctx, removeOrderItem, itemID)
	return err
}

const updateItemQuantity = `-- name: UpdateItemQuantity :exec
UPDATE    order_items
SET       quantity = ?
WHERE     item_id = ?
`

// Update item quantity
func (q *Queries) UpdateItemQuantity(ctx context.Context, quantity int64, itemID int64) error {
	_, err := q.db.ExecContext(ctx, updateItemQuantity, quantity, itemID)
	return err
}
