// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 050002_transactions.sql

package db

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT    INTO transactions (order_id, method_id, amount, status, external_id)
VALUES    (?, ?, ?, ?, ?)
RETURNING transaction_id, order_id, method_id, amount, status, external_id, created_at
`

type CreateTransactionParams struct {
	OrderID    int64   `json:"order_id"`
	MethodID   int64   `json:"method_id"`
	Amount     float64 `json:"amount"`
	Status     string  `json:"status"`
	ExternalID string  `json:"external_id"`
}

// Record payment transaction
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.OrderID,
		arg.MethodID,
		arg.Amount,
		arg.Status,
		arg.ExternalID,
	)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MethodID,
		&i.Amount,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const findTransactionByExternalID = `-- name: FindTransactionByExternalID :one
SELECT    transaction_id, order_id, method_id, amount, status, external_id, created_at
FROM      transactions
WHERE     external_id = ?
`

// Find transaction by gateway reference
func (q *Queries) FindTransactionByExternalID(ctx context.Context, externalID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, findTransactionByExternalID, externalID)
	var i Transaction
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MethodID,
		&i.Amount,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyPaymentReport = `-- name: GetDailyPaymentReport :many
SELECT    DATE (t.created_at) AS payment_date,
          m.name              AS METHOD,
          COUNT(*) FILTER     (
          WHERE     t.status = 'success'
          ) AS success_count,
          SUM(t.amount) FILTER (
          WHERE     t.status = 'success'
          ) AS success_total,
          COUNT(*) FILTER (
          WHERE     t.status = 'failed'
          ) AS failed_count,
          SUM(t.amount) FILTER (
          WHERE     t.status = 'failed'
          ) AS failed_total
FROM      transactions t
JOIN      payment_methods m ON t.method_id = m.method_id
WHERE     t.created_at BETWEEN ? AND ?
GROUP BY  payment_date,
          METHOD
ORDER BY  payment_date DESC
`

type GetDailyPaymentReportRow struct {
	PaymentDate  interface{}     `json:"payment_date"`
	Method       string          `json:"method"`
	SuccessCount int64           `json:"success_count"`
	SuccessTotal sql.NullFloat64 `json:"success_total"`
	FailedCount  int64           `json:"failed_count"`
	FailedTotal  sql.NullFloat64 `json:"failed_total"`
}

func (q *Queries) GetDailyPaymentReport(ctx context.Context, fromCreatedAt sql.NullTime, toCreatedAt sql.NullTime) ([]GetDailyPaymentReportRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyPaymentReport, fromCreatedAt, toCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyPaymentReportRow
	for rows.Next() {
		var i GetDailyPaymentReportRow
		if err := rows.Scan(
			&i.PaymentDate,
			&i.Method,
			&i.SuccessCount,
			&i.SuccessTotal,
			&i.FailedCount,
			&i.FailedTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailedTransactions = `-- name: GetFailedTransactions :many
SELECT    t.transaction_id, t.order_id, t.method_id, t.amount, t.status, t.external_id, t.created_at,
          m.name           AS payment_method,
          o.guest_order_id,
          u.email          AS user_email
FROM      transactions t
JOIN      payment_methods m ON t.method_id = m.method_id
JOIN      orders o ON t.order_id = o.order_id
LEFT JOIN users u ON o.user_id = u.user_id
WHERE     t.status = 'failed'
`

type GetFailedTransactionsRow struct {
	TransactionID int64          `json:"transaction_id"`
	OrderID       int64          `json:"order_id"`
	MethodID      int64          `json:"method_id"`
	Amount        float64        `json:"amount"`
	Status        string         `json:"status"`
	ExternalID    string         `json:"external_id"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	PaymentMethod string         `json:"payment_method"`
	GuestOrderID  sql.NullInt64  `json:"guest_order_id"`
	UserEmail     sql.NullString `json:"user_email"`
}

// Find failed transactions
func (q *Queries) GetFailedTransactions(ctx context.Context) ([]GetFailedTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFailedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedTransactionsRow
	for rows.Next() {
		var i GetFailedTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MethodID,
			&i.Amount,
			&i.Status,
			&i.ExternalID,
			&i.CreatedAt,
			&i.PaymentMethod,
			&i.GuestOrderID,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT    t.transaction_id, t.order_id, t.method_id, t.amount, t.status, t.external_id, t.created_at,
          m.name  AS payment_method,
          o.total AS order_total
FROM      transactions t
JOIN      payment_methods m ON t.method_id = m.method_id
JOIN      orders o ON t.order_id = o.order_id
WHERE     t.transaction_id = ?
`

type GetTransactionByIDRow struct {
	TransactionID int64        `json:"transaction_id"`
	OrderID       int64        `json:"order_id"`
	MethodID      int64        `json:"method_id"`
	Amount        float64      `json:"amount"`
	Status        string       `json:"status"`
	ExternalID    string       `json:"external_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	PaymentMethod string       `json:"payment_method"`
	OrderTotal    float64      `json:"order_total"`
}

// Get transaction by ID
func (q *Queries) GetTransactionByID(ctx context.Context, transactionID int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, transactionID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.TransactionID,
		&i.OrderID,
		&i.MethodID,
		&i.Amount,
		&i.Status,
		&i.ExternalID,
		&i.CreatedAt,
		&i.PaymentMethod,
		&i.OrderTotal,
	)
	return i, err
}

const getTransactionsByOrder = `-- name: GetTransactionsByOrder :many
SELECT    t.transaction_id, t.order_id, t.method_id, t.amount, t.status, t.external_id, t.created_at,
          m.name AS payment_method
FROM      transactions t
JOIN      payment_methods m ON t.method_id = m.method_id
WHERE     t.order_id = ?
ORDER BY  t.created_at DESC
`

type GetTransactionsByOrderRow struct {
	TransactionID int64        `json:"transaction_id"`
	OrderID       int64        `json:"order_id"`
	MethodID      int64        `json:"method_id"`
	Amount        float64      `json:"amount"`
	Status        string       `json:"status"`
	ExternalID    string       `json:"external_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
	PaymentMethod string       `json:"payment_method"`
}

// Get order payment history
func (q *Queries) GetTransactionsByOrder(ctx context.Context, orderID int64) ([]GetTransactionsByOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsByOrderRow
	for rows.Next() {
		var i GetTransactionsByOrderRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.OrderID,
			&i.MethodID,
			&i.Amount,
			&i.Status,
			&i.ExternalID,
			&i.CreatedAt,
			&i.PaymentMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE    transactions
SET       status = ?
WHERE     transaction_id = ?
`

// Update transaction status
func (q *Queries) UpdateTransactionStatus(ctx context.Context, status string, transactionID int64) error {
	_, err := q.db.ExecContext(ctx, updateTransactionStatus, status, transactionID)
	return err
}
