// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 050001_payment_methods.sql

package db

import (
	"context"
	"database/sql"
)

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT    INTO payment_methods (NAME, is_active)
VALUES    (?, ?)
RETURNING method_id, name, is_active
`

// Create payment method (Admin only)
func (q *Queries) CreatePaymentMethod(ctx context.Context, name string, isActive sql.NullInt64) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, createPaymentMethod, name, isActive)
	var i PaymentMethod
	err := row.Scan(&i.MethodID, &i.Name, &i.IsActive)
	return i, err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT    method_id, name, is_active
FROM      payment_methods
WHERE     method_id = ?
`

// Get payment method by ID
func (q *Queries) GetPaymentMethodByID(ctx context.Context, methodID int64) (PaymentMethod, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByID, methodID)
	var i PaymentMethod
	err := row.Scan(&i.MethodID, &i.Name, &i.IsActive)
	return i, err
}

const listActivePaymentMethods = `-- name: ListActivePaymentMethods :many
SELECT    method_id, name, is_active
FROM      payment_methods
WHERE     is_active = 1
ORDER BY  NAME
`

// List active payment methods
func (q *Queries) ListActivePaymentMethods(ctx context.Context) ([]PaymentMethod, error) {
	rows, err := q.db.QueryContext(ctx, listActivePaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethod
	for rows.Next() {
		var i PaymentMethod
		if err := rows.Scan(&i.MethodID, &i.Name, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentMethodStatus = `-- name: UpdatePaymentMethodStatus :exec
UPDATE    payment_methods
SET       is_active = ?
WHERE     method_id = ?
`

// Update payment method status
func (q *Queries) UpdatePaymentMethodStatus(ctx context.Context, isActive sql.NullInt64, methodID int64) error {
	_, err := q.db.ExecContext(ctx, updatePaymentMethodStatus, isActive, methodID)
	return err
}
