// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 060001_logs.sql

package db

import (
	"context"
	"database/sql"
)

const createLog = `-- name: CreateLog :one
INSERT    INTO logs (user_id, action_type, details, ip_address)
VALUES    (?, ?, ?, ?)
RETURNING log_id, user_id, action_type, details, ip_address, created_at
`

type CreateLogParams struct {
	UserID     sql.NullInt64  `json:"user_id"`
	ActionType string         `json:"action_type"`
	Details    string         `json:"details"`
	IpAddress  sql.NullString `json:"ip_address"`
}

// Log system event
func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.UserID,
		arg.ActionType,
		arg.Details,
		arg.IpAddress,
	)
	var i Log
	err := row.Scan(
		&i.LogID,
		&i.UserID,
		&i.ActionType,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldLogs = `-- name: DeleteOldLogs :exec
DELETE    FROM logs
WHERE     created_at < ?
`

// Prune old logs
func (q *Queries) DeleteOldLogs(ctx context.Context, createdAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, deleteOldLogs, createdAt)
	return err
}

const getLogs = `-- name: GetLogs :many
SELECT    l.log_id, l.user_id, l.action_type, l.details, l.ip_address, l.created_at,
          u.email AS user_email
FROM      logs l
LEFT JOIN users u ON l.user_id = u.user_id
ORDER BY  l.created_at DESC
LIMIT     ?
`

type GetLogsRow struct {
	LogID      int64          `json:"log_id"`
	UserID     sql.NullInt64  `json:"user_id"`
	ActionType string         `json:"action_type"`
	Details    string         `json:"details"`
	IpAddress  sql.NullString `json:"ip_address"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UserEmail  sql.NullString `json:"user_email"`
}

// Get recent logs
func (q *Queries) GetLogs(ctx context.Context, limit int64) ([]GetLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLogsRow
	for rows.Next() {
		var i GetLogsRow
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.ActionType,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsByAction = `-- name: GetLogsByAction :many
SELECT    log_id, user_id, action_type, details, ip_address, created_at
FROM      logs
WHERE     action_type = ?
ORDER BY  created_at DESC
`

// Filter logs by action type
func (q *Queries) GetLogsByAction(ctx context.Context, actionType string) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogsByAction, actionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.ActionType,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivity = `-- name: GetUserActivity :many
SELECT    log_id, user_id, action_type, details, ip_address, created_at
FROM      logs
WHERE     user_id = ?
ORDER BY  created_at DESC
`

// Get user activity log
func (q *Queries) GetUserActivity(ctx context.Context, userID sql.NullInt64) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getUserActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.ActionType,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
