// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 060002_recommendations.sql

package db

import (
	"context"
	"database/sql"
)

const clearUserRecommendations = `-- name: ClearUserRecommendations :exec
DELETE    FROM recommendations
WHERE     user_id = ?
`

// Clear user recommendations
func (q *Queries) ClearUserRecommendations(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, clearUserRecommendations, userID)
	return err
}

const createRecommendation = `-- name: CreateRecommendation :one
INSERT    INTO recommendations (user_id, product_id, score)
VALUES    (?, ?, ?)
RETURNING recommendation_id, user_id, product_id, score, created_at
`

// Add recommendation
func (q *Queries) CreateRecommendation(ctx context.Context, userID int64, productID int64, score float64) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, createRecommendation, userID, productID, score)
	var i Recommendation
	err := row.Scan(
		&i.RecommendationID,
		&i.UserID,
		&i.ProductID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const getRecommendations = `-- name: GetRecommendations :many
SELECT    r.recommendation_id, r.user_id, r.product_id, r.score, r.created_at,
          p.name        AS product_name,
          p.base_price,
          p.description
FROM      recommendations r
JOIN      products p ON r.product_id = p.product_id
WHERE     r.user_id = ?
ORDER BY  r.score DESC
LIMIT     ?
`

type GetRecommendationsRow struct {
	RecommendationID int64          `json:"recommendation_id"`
	UserID           int64          `json:"user_id"`
	ProductID        int64          `json:"product_id"`
	Score            float64        `json:"score"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	ProductName      string         `json:"product_name"`
	BasePrice        float64        `json:"base_price"`
	Description      sql.NullString `json:"description"`
}

// Get user recommendations
func (q *Queries) GetRecommendations(ctx context.Context, userID int64, limit int64) ([]GetRecommendationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecommendations, userID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecommendationsRow
	for rows.Next() {
		var i GetRecommendationsRow
		if err := rows.Scan(
			&i.RecommendationID,
			&i.UserID,
			&i.ProductID,
			&i.Score,
			&i.CreatedAt,
			&i.ProductName,
			&i.BasePrice,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshRecommendations = `-- name: RefreshRecommendations :exec
DELETE    FROM recommendations
WHERE     user_id = ?
`

func (q *Queries) RefreshRecommendations(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, refreshRecommendations, userID)
	return err
}

const removeOldRecommendations = `-- name: RemoveOldRecommendations :exec
DELETE    FROM recommendations
WHERE     created_at < ?
`

// Remove stale recommendations
func (q *Queries) RemoveOldRecommendations(ctx context.Context, createdAt sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, removeOldRecommendations, createdAt)
	return err
}

const updateRecommendationScore = `-- name: UpdateRecommendationScore :exec
UPDATE    recommendations
SET       score = ?
WHERE     recommendation_id = ?
`

// Update recommendation score
func (q *Queries) UpdateRecommendationScore(ctx context.Context, score float64, recommendationID int64) error {
	_, err := q.db.ExecContext(ctx, updateRecommendationScore, score, recommendationID)
	return err
}
