// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Category struct {
	CategoryID int64         `json:"category_id"`
	Name       string        `json:"name"`
	ParentID   sql.NullInt64 `json:"parent_id"`
}

type GuestOrder struct {
	GuestOrderID     int64        `json:"guest_order_id"`
	Email            string       `json:"email"`
	EncryptedAddress string       `json:"encrypted_address"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type InventoryLocation struct {
	LocationID int64  `json:"location_id"`
	Name       string `json:"name"`
	City       string `json:"city"`
	Region     string `json:"region"`
}

type Log struct {
	LogID      int64          `json:"log_id"`
	UserID     sql.NullInt64  `json:"user_id"`
	ActionType string         `json:"action_type"`
	Details    string         `json:"details"`
	IpAddress  sql.NullString `json:"ip_address"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Order struct {
	OrderID         int64         `json:"order_id"`
	UserID          sql.NullInt64 `json:"user_id"`
	GuestOrderID    sql.NullInt64 `json:"guest_order_id"`
	Total           float64       `json:"total"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	CurrentStatusID int64         `json:"current_status_id"`
}

type OrderItem struct {
	ItemID    int64   `json:"item_id"`
	OrderID   int64   `json:"order_id"`
	VariantID int64   `json:"variant_id"`
	Quantity  int64   `json:"quantity"`
	Price     float64 `json:"price"`
}

type OrderStatus struct {
	StatusID   int64  `json:"status_id"`
	StatusName string `json:"status_name"`
}

type OrderStatusHistory struct {
	HistoryID int64        `json:"history_id"`
	OrderID   int64        `json:"order_id"`
	StatusID  int64        `json:"status_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PaymentMethod struct {
	MethodID int64         `json:"method_id"`
	Name     string        `json:"name"`
	IsActive sql.NullInt64 `json:"is_active"`
}

type Product struct {
	ProductID   int64          `json:"product_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   float64        `json:"base_price"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type ProductAttribute struct {
	AttributeID    int64  `json:"attribute_id"`
	ProductID      int64  `json:"product_id"`
	AttributeName  string `json:"attribute_name"`
	AttributeValue string `json:"attribute_value"`
}

type ProductCategory struct {
	ProductID  int64 `json:"product_id"`
	CategoryID int64 `json:"category_id"`
}

type ProductVariant struct {
	VariantID      int64         `json:"variant_id"`
	ProductID      int64         `json:"product_id"`
	Sku            string        `json:"sku"`
	Price          float64       `json:"price"`
	Attributes     string        `json:"attributes"`
	AllowBackorder sql.NullInt64 `json:"allow_backorder"`
}

type Recommendation struct {
	RecommendationID int64        `json:"recommendation_id"`
	UserID           int64        `json:"user_id"`
	ProductID        int64        `json:"product_id"`
	Score            float64      `json:"score"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type Stock struct {
	StockID           int64         `json:"stock_id"`
	VariantID         int64         `json:"variant_id"`
	LocationID        int64         `json:"location_id"`
	Quantity          int64         `json:"quantity"`
	LowStockThreshold sql.NullInt64 `json:"low_stock_threshold"`
	LowStockAlert     sql.NullInt64 `json:"low_stock_alert"`
}

type Transaction struct {
	TransactionID int64        `json:"transaction_id"`
	OrderID       int64        `json:"order_id"`
	MethodID      int64        `json:"method_id"`
	Amount        float64      `json:"amount"`
	Status        string       `json:"status"`
	ExternalID    string       `json:"external_id"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type User struct {
	UserID       int64          `json:"user_id"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	LastLogin    sql.NullTime   `json:"last_login"`
	IsActive     sql.NullInt64  `json:"is_active"`
}

type UserAddress struct {
	AddressID        int64         `json:"address_id"`
	UserID           int64         `json:"user_id"`
	EncryptedAddress string        `json:"encrypted_address"`
	City             string        `json:"city"`
	Region           string        `json:"region"`
	Phone            []byte        `json:"phone"`
	IsDefault        sql.NullInt64 `json:"is_default"`
	CreatedAt        sql.NullTime  `json:"created_at"`
}

type UserRole struct {
	RoleID   int64  `json:"role_id"`
	RoleName string `json:"role_name"`
}

type UserRoleAssignment struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

type UserSocialLogin struct {
	SocialID   int64  `json:"social_id"`
	UserID     int64  `json:"user_id"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}
