AWSTemplateFormatVersion: "2010-09-09"
Description: Root Stack for the project that consumes other CloudFormation templates

Parameters:
  ProjectName:
    Type: String
    Description: Project name
  Stage:
    Type: String
    Description: Stage of the API Gateway
  S3BucketStackName:
    Type: String
    Description: S3 Bucket for Stack and Resources

  S3BucketLambdasPrefix:
    Type: String
    Description: S3 Bucket for Stack and Resources
    Default: infrastructure/lambdas

Resources:
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketStackName}/infrastructure/cognito.yml"
      Parameters:
        ProjectName: !Ref ProjectName
        S3BucketLambdasPrefix: !Ref S3BucketLambdasPrefix
        S3BucketStackName: !Ref S3BucketStackName
        # PreSignupExists: "false"
        PostConfirmationExists: "true"
        # PreAuthenticationExists: "false"
        # PostAuthenticationExists: "true"
        # PreTokenGenerationExists: "false"

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CognitoStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketStackName}/infrastructure/apigateway.yml"
      Parameters:
        ProjectName: !Ref ProjectName
        Stage: !Ref Stage
        S3BucketStackName: !Ref S3BucketStackName
        S3BucketLambdasPrefix: !Ref S3BucketLambdasPrefix
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.CognitoUserPoolId
        CognitoUserPoolClient: !GetAtt CognitoStack.Outputs.CognitoUserPoolClient

Outputs:
  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolId
    Description: The ID of the Cognito User Pool
  CognitoUserPoolDomain:
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolDomain
    Description: The domain name of the Cognito User Pool
  CognitoUserPoolClient:
    Value: !GetAtt CognitoStack.Outputs.CognitoUserPoolClient
    Description: The User Pool Client
